name: Update agencies.json

on:
  schedule:
    - cron: '37 * * * *' # avoid start of hour contention
  workflow_dispatch:

jobs:
  update:
    environment: prod
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0

      - name: Update agencies.json
        env:
          ELASTIC_URL: ${{ secrets.ELASTIC_URL }}
          ELASTIC_INDEX: ${{ secrets.ELASTIC_INDEX }}
          ELASTIC_USER: ${{ secrets.ELASTIC_USER }}
          ELASTIC_PASS: ${{ secrets.ELASTIC_PASS }}
        run: uv run fetch_agencies.py agencies.json

      - name: Commit if agencies.json changed
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6.0.1
        with:
          commit_message: "Update agencies.json"
          file_pattern: agencies.json